# moco_control Settings -----------------------
# Settings for ros_control control loop
moco_hw_interface:
  loop_hz: 100
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   data_rate: 100
   chain: "msa6-1001"
   joints:
      - joint_J1
      - joint_J2
      - joint_J3
      - joint_J4
      - joint_J5
      - joint_J6
   simulated_joints:
     joint_J1:
         serial: 1001
     joint_J2:
         serial: 1002
     joint_J3:
         serial: 1003
     joint_J4:
         serial: 1004
     joint_J5:
         serial: 1005
     joint_J6:
         serial: 1006

   sim_control_mode: 1 # 0: position, 1: velocity
   simulator:
      host: localhost
# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
      - joint_J1
      - joint_J2
      - joint_J3
      - joint_J4
      - joint_J5
      - joint_J6
   constraints:
      goal_time: 5.0
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      joint_J1:
          trajectory: 0.60
          goal:       0.15
      joint_J2:
          trajectory: 0.60
          goal:       0.15
   # gains:
   #     joint_J1: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint_J2: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}

    # state_publish_rate:  50 # Defaults to 50
    # action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately
joint_J1_position_controller:
   type: position_controllers/JointPositionController
   joint: joint_J1
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint_J2_position_controller:
   type: position_controllers/JointPositionController
   joint: joint_J2
   pid: {p: 100.0, i: 0.01, d: 10.0}

# Group Position Controllers ---------------------------------------
# Allows to send single ROS msg of Float64MultiArray to all joints
joint_position_controller:
   type: position_controllers/JointGroupPositionController
   joints:
      - joint_J1
      - joint_J2
      - joint_J3
      - joint_J4
      - joint_J5
      - joint_J6
