controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_J1
      - joint_J2
      - joint_J3
      - joint_J4
      - joint_J5
      - joint_J6
  - name: fake_endeffector_controller
    joints:
      - bellows_link_joint
      - right_spoon_joint
