# MoveIt-specific settings
controller_list:
  - name: arm_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_J1
      - joint_J2
      - joint_J3
      - joint_J4
      - joint_J5
      - joint_J6
